
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('users').del()
    .then(function () {
      // Inserts seed entries
      return knex('users').insert([
        { id: 1, username:'a', password:'$2a$10$Ynce0EsLn4dA1ESQyM0sgucKseOsYIIEdwg7OJAbvZ1vqmKM5GhA2', firstname: 'a', lastname: 'b', email: 'a@a.com', age: 26,  street: null, city: null, zip: null, state: null, country: null, phone: null, description: "I am a new developer and super excited to start getting help with iHelp", tagline: "I love JavaScipt", image: "https://media.licdn.com/dms/image/C5603AQH1JBVcGG9W6g/profile-displayphoto-shrink_200_200/0?e=1556755200&v=beta&t=ST8HB4WG63mJq973cm8G4XmY4Hewik457_L8G0yz0sQ", skill: 'New Developer', github: null, linkedin: null, website: null, twitter: null, facebook: null,google_hangout: null, skype: null, paypal: null, billing_link: null, school: null, org: null, company: null, repl: null, codepen: null, codewars: null, queue_status: 'offline' },
        { id: 2, username:'b', password:'$2a$10$Ynce0EsLn4dA1ESQyM0sgucKseOsYIIEdwg7OJAbvZ1vqmKM5GhA2', firstname: 'b', lastname: 'b', email: 'a@a.com', age: 26,  street: null, city: null, zip: null, state: null, country: null, phone: null, description: "I am a new developer and super excited to start getting help with iHelp", tagline: "I love Helping", image: "https://media.licdn.com/dms/image/C5603AQH1JBVcGG9W6g/profile-displayphoto-shrink_200_200/0?e=1556755200&v=beta&t=ST8HB4WG63mJq973cm8G4XmY4Hewik457_L8G0yz0sQ", skill: 'New Developer', github: null, linkedin: null, website: null, twitter: null, facebook: null,google_hangout: null, skype: null, paypal: null, billing_link: null, school: null, org: null, company: null, repl: null, codepen: null, codewars: null, queue_status: 'offline' },
        { id: 3, username:'c', password:'$2a$10$Ynce0EsLn4dA1ESQyM0sgucKseOsYIIEdwg7OJAbvZ1vqmKM5GhA2', firstname: 'c', lastname: 'b', email: 'a@a.com', age: 26,  street: null, city: null, zip: null, state: null, country: null, phone: null, description: "I am a new developer and super excited to start getting help with iHelp", tagline: "I love the web!", image: "https://media.licdn.com/dms/image/C5603AQH1JBVcGG9W6g/profile-displayphoto-shrink_200_200/0?e=1556755200&v=beta&t=ST8HB4WG63mJq973cm8G4XmY4Hewik457_L8G0yz0sQ", skill: 'New Developer', github: null, linkedin: null, website: null, twitter: null, facebook: null,google_hangout: null, skype: null, paypal: null, billing_link: null, school: null, org: null, company: null, repl: null, codepen: null, codewars: null, queue_status: 'offline' },
        { id: 4, username:'d', password:'$2a$10$Ynce0EsLn4dA1ESQyM0sgucKseOsYIIEdwg7OJAbvZ1vqmKM5GhA2', firstname: 'd', lastname: 'b', email: 'a@a.com', age: 26,  street: null, city: null, zip: null, state: null, country: null, phone: null, description: "I am a new developer and super excited to start getting help with iHelp", tagline: "I love JavaScipt", image: "https://media.licdn.com/dms/image/C5603AQH1JBVcGG9W6g/profile-displayphoto-shrink_200_200/0?e=1556755200&v=beta&t=ST8HB4WG63mJq973cm8G4XmY4Hewik457_L8G0yz0sQ", skill: 'New Developer', github: null, linkedin: null, website: null, twitter: null, facebook: null,google_hangout: null, skype: null, paypal: null, billing_link: null, school: null, org: null, company: null, repl: null, codepen: null, codewars: null, queue_status: 'offline' },
        { id: 5, username:'e', password:'$2a$10$Ynce0EsLn4dA1ESQyM0sgucKseOsYIIEdwg7OJAbvZ1vqmKM5GhA2', firstname: 'e', lastname: 'b', email: 'a@a.com', age: 26,  street: null, city: null, zip: null, state: null, country: null, phone: null, description: "I am a new developer and super excited to start getting help with iHelp", tagline: "I love JavaScipt", image: "https://media.licdn.com/dms/image/C5603AQH1JBVcGG9W6g/profile-displayphoto-shrink_200_200/0?e=1556755200&v=beta&t=ST8HB4WG63mJq973cm8G4XmY4Hewik457_L8G0yz0sQ", skill: 'New Developer', github: null, linkedin: null, website: null, twitter: null, facebook: null,google_hangout: null, skype: null, paypal: null, billing_link: null, school: null, org: null, company: null, repl: null, codepen: null, codewars: null, queue_status: 'offline' },
        { id: 6, username:'f', password:'$2a$10$Ynce0EsLn4dA1ESQyM0sgucKseOsYIIEdwg7OJAbvZ1vqmKM5GhA2', firstname: 'f', lastname: 'b', email: 'a@a.com', age: 26,  street: null, city: null, zip: null, state: null, country: null, phone: null, description: "I am a new developer and super excited to start getting help with iHelp", tagline: "I love JavaScipt", image: "https://media.licdn.com/dms/image/C5603AQH1JBVcGG9W6g/profile-displayphoto-shrink_200_200/0?e=1556755200&v=beta&t=ST8HB4WG63mJq973cm8G4XmY4Hewik457_L8G0yz0sQ", skill: 'New Developer', github: null, linkedin: null, website: null, twitter: null, facebook: null,google_hangout: null, skype: null, paypal: null, billing_link: null, school: null, org: null, company: null, repl: null, codepen: null, codewars: null, queue_status: 'offline' },
        { id: 7, username:'g', password:'$2a$10$Ynce0EsLn4dA1ESQyM0sgucKseOsYIIEdwg7OJAbvZ1vqmKM5GhA2', firstname: 'g', lastname: 'b', email: 'a@a.com', age: 26,  street: null, city: null, zip: null, state: null, country: null, phone: null, description: "I am a new developer and super excited to start getting help with iHelp", tagline: "I love JavaScipt", image: "https://media.licdn.com/dms/image/C5603AQH1JBVcGG9W6g/profile-displayphoto-shrink_200_200/0?e=1556755200&v=beta&t=ST8HB4WG63mJq973cm8G4XmY4Hewik457_L8G0yz0sQ", skill: 'New Developer', github: null, linkedin: null, website: null, twitter: null, facebook: null,google_hangout: null, skype: null, paypal: null, billing_link: null, school: null, org: null, company: null, repl: null, codepen: null, codewars: null, queue_status: 'offline' },
        { id: 8, username:'h', password:'$2a$10$Ynce0EsLn4dA1ESQyM0sgucKseOsYIIEdwg7OJAbvZ1vqmKM5GhA2', firstname: 'h', lastname: 'b', email: 'a@a.com', age: 26,  street: null, city: null, zip: null, state: null, country: null, phone: null, description: "I am a new developer and super excited to start getting help with iHelp", tagline: "I love JavaScipt", image: "https://media.licdn.com/dms/image/C5603AQH1JBVcGG9W6g/profile-displayphoto-shrink_200_200/0?e=1556755200&v=beta&t=ST8HB4WG63mJq973cm8G4XmY4Hewik457_L8G0yz0sQ", skill: 'New Developer', github: null, linkedin: null, website: null, twitter: null, facebook: null,google_hangout: null, skype: null, paypal: null, billing_link: null, school: null, org: null, company: null, repl: null, codepen: null, codewars: null, queue_status: 'offline' },
        { id: 9, username:'i', password:'$2a$10$Ynce0EsLn4dA1ESQyM0sgucKseOsYIIEdwg7OJAbvZ1vqmKM5GhA2', firstname: 'i', lastname: 'b', email: 'a@a.com', age: 26,  street: null, city: null, zip: null, state: null, country: null, phone: null, description: "I am a new developer and super excited to start getting help with iHelp", tagline: "I love JavaScipt", image: "https://media.licdn.com/dms/image/C5603AQH1JBVcGG9W6g/profile-displayphoto-shrink_200_200/0?e=1556755200&v=beta&t=ST8HB4WG63mJq973cm8G4XmY4Hewik457_L8G0yz0sQ", skill: 'New Developer', github: null, linkedin: null, website: null, twitter: null, facebook: null,google_hangout: null, skype: null, paypal: null, billing_link: null, school: null, org: null, company: null, repl: null, codepen: null, codewars: null, queue_status: 'offline' },
        { id: 10, username:'j', password:'$2a$10$Ynce0EsLn4dA1ESQyM0sgucKseOsYIIEdwg7OJAbvZ1vqmKM5GhA2', firstname: 'j', lastname: 'b', email: 'a@a.com', age: 26,  street: null, city: null, zip: null, state: null, country: null, phone: null, description: "I am a new developer and super excited to start getting help with iHelp", tagline: "I love JavaScipt", image: "https://media.licdn.com/dms/image/C5603AQH1JBVcGG9W6g/profile-displayphoto-shrink_200_200/0?e=1556755200&v=beta&t=ST8HB4WG63mJq973cm8G4XmY4Hewik457_L8G0yz0sQ", skill: 'New Developer', github: null, linkedin: null, website: null, twitter: null, facebook: null,google_hangout: null, skype: null, paypal: null, billing_link: null, school: null, org: null, company: null, repl: null, codepen: null, codewars: null, queue_status: 'offline'}
      ]);
    }).then(() => {
      return knex.raw(
        `SELECT setval('users_id_seq', (SELECT MAX(id) FROM users));`
      )
    })
};
