
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('users').del()
    .then(function () {
      // Inserts seed entries
      return knex('users').insert([
        { id: 1, username:'a', password:'$2a$10$Ynce0EsLn4dA1ESQyM0sgucKseOsYIIEdwg7OJAbvZ1vqmKM5GhA2', firstname: 'a', lastname: 'b', email: 'a@a.com', age: 26,  street: null, city: null, zip: null, state: null, country: null, phone: null, description: null, tagline: null, image: null, skill: null, github: null, linkedin: null, website: null, twitter: null, facebook: null,google_hangout: null, skype: null, paypal: null, billing_link: null, school: null, org: null, company: null, repl: null, codepen: null, codewars: null, queue_status: null },
        { id: 2, username:'b', password:'$2a$10$Ynce0EsLn4dA1ESQyM0sgucKseOsYIIEdwg7OJAbvZ1vqmKM5GhA2', firstname: 'b', lastname: 'b', email: 'a@a.com', age: 26,  street: null, city: null, zip: null, state: null, country: null, phone: null, description: null, tagline: null, image: null, skill: null, github: null, linkedin: null, website: null, twitter: null, facebook: null,google_hangout: null, skype: null, paypal: null, billing_link: null, school: null, org: null, company: null, repl: null, codepen: null, codewars: null, queue_status: null },
        { id: 3, username:'c', password:'$2a$10$Ynce0EsLn4dA1ESQyM0sgucKseOsYIIEdwg7OJAbvZ1vqmKM5GhA2', firstname: 'c', lastname: 'b', email: 'a@a.com', age: 26,  street: null, city: null, zip: null, state: null, country: null, phone: null, description: null, tagline: null, image: null, skill: null, github: null, linkedin: null, website: null, twitter: null, facebook: null,google_hangout: null, skype: null, paypal: null, billing_link: null, school: null, org: null, company: null, repl: null, codepen: null, codewars: null, queue_status: null },
        { id: 4, username:'d', password:'$2a$10$Ynce0EsLn4dA1ESQyM0sgucKseOsYIIEdwg7OJAbvZ1vqmKM5GhA2', firstname: 'd', lastname: 'b', email: 'a@a.com', age: 26,  street: null, city: null, zip: null, state: null, country: null, phone: null, description: null, tagline: null, image: null, skill: null, github: null, linkedin: null, website: null, twitter: null, facebook: null,google_hangout: null, skype: null, paypal: null, billing_link: null, school: null, org: null, company: null, repl: null, codepen: null, codewars: null, queue_status: null },
        { id: 5, username:'e', password:'$2a$10$Ynce0EsLn4dA1ESQyM0sgucKseOsYIIEdwg7OJAbvZ1vqmKM5GhA2', firstname: 'e', lastname: 'b', email: 'a@a.com', age: 26,  street: null, city: null, zip: null, state: null, country: null, phone: null, description: null, tagline: null, image: null, skill: null, github: null, linkedin: null, website: null, twitter: null, facebook: null,google_hangout: null, skype: null, paypal: null, billing_link: null, school: null, org: null, company: null, repl: null, codepen: null, codewars: null, queue_status: null },
        { id: 6, username:'f', password:'$2a$10$Ynce0EsLn4dA1ESQyM0sgucKseOsYIIEdwg7OJAbvZ1vqmKM5GhA2', firstname: 'f', lastname: 'b', email: 'a@a.com', age: 26,  street: null, city: null, zip: null, state: null, country: null, phone: null, description: null, tagline: null, image: null, skill: null, github: null, linkedin: null, website: null, twitter: null, facebook: null,google_hangout: null, skype: null, paypal: null, billing_link: null, school: null, org: null, company: null, repl: null, codepen: null, codewars: null, queue_status: null },
        { id: 7, username:'g', password:'$2a$10$Ynce0EsLn4dA1ESQyM0sgucKseOsYIIEdwg7OJAbvZ1vqmKM5GhA2', firstname: 'g', lastname: 'b', email: 'a@a.com', age: 26,  street: null, city: null, zip: null, state: null, country: null, phone: null, description: null, tagline: null, image: null, skill: null, github: null, linkedin: null, website: null, twitter: null, facebook: null,google_hangout: null, skype: null, paypal: null, billing_link: null, school: null, org: null, company: null, repl: null, codepen: null, codewars: null, queue_status: null },
        { id: 8, username:'h', password:'$2a$10$Ynce0EsLn4dA1ESQyM0sgucKseOsYIIEdwg7OJAbvZ1vqmKM5GhA2', firstname: 'h', lastname: 'b', email: 'a@a.com', age: 26,  street: null, city: null, zip: null, state: null, country: null, phone: null, description: null, tagline: null, image: null, skill: null, github: null, linkedin: null, website: null, twitter: null, facebook: null,google_hangout: null, skype: null, paypal: null, billing_link: null, school: null, org: null, company: null, repl: null, codepen: null, codewars: null, queue_status: null },
        { id: 9, username:'i', password:'$2a$10$Ynce0EsLn4dA1ESQyM0sgucKseOsYIIEdwg7OJAbvZ1vqmKM5GhA2', firstname: 'i', lastname: 'b', email: 'a@a.com', age: 26,  street: null, city: null, zip: null, state: null, country: null, phone: null, description: null, tagline: null, image: null, skill: null, github: null, linkedin: null, website: null, twitter: null, facebook: null,google_hangout: null, skype: null, paypal: null, billing_link: null, school: null, org: null, company: null, repl: null, codepen: null, codewars: null, queue_status: null },
        { id: 10, username:'j', password:'$2a$10$Ynce0EsLn4dA1ESQyM0sgucKseOsYIIEdwg7OJAbvZ1vqmKM5GhA2', firstname: 'j', lastname: 'b', email: 'a@a.com', age: 26,  street: null, city: null, zip: null, state: null, country: null, phone: null, description: null, tagline: null, image: null, skill: null, github: null, linkedin: null, website: null, twitter: null, facebook: null,google_hangout: null, skype: null, paypal: null, billing_link: null, school: null, org: null, company: null, repl: null, codepen: null, codewars: null, queue_status: null}
      ]);
    });
};
