exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('users').del()
    .then(function () {
      // Inserts seed entries
      return knex('users').insert([
        { id: 1, username:'1', password:'$2a$10$Ynce0EsLn4dA1ESQyM0sgucKseOsYIIEdwg7OJAbvZ1vqmKM5GhA2', firstname: 'Elon', lastname: 'Musk', email: 'a@a.com', age: 26,  street: null, city: null, zip: null, state: null, country: null, phone: null, description: "I leard to code as a child in my bedroom. I used my coding skills to create the multi-billion dollar company PayPal. ", tagline: "Lets create a better world with code.", image: "https://www.biography.com/.image/t_share/MTE1ODA0OTcxOTUyMDE0ODYx/elon-musk-20837159-1-402.png", skill: 'Mid. Developer', github: null, linkedin: null, website: null, twitter: null, facebook: null,google_hangout: null, skype: null, paypal: null, billing_link: null, school: null, org: null, company: null, repl: null, codepen: null, codewars: null, queue_status: 'available', online: 'online' },
        { id: 2, username:'2', password:'$2a$10$Ynce0EsLn4dA1ESQyM0sgucKseOsYIIEdwg7OJAbvZ1vqmKM5GhA2', firstname: 'Steve', lastname: 'Jobs', email: 'a@a.com', age: 26,  street: null, city: null, zip: null, state: null, country: null, phone: null, description: "I used coding to create Apple and revolutionalized computer user interfaces and later created the modern smart phone.", tagline: "I love to solve big problems with great products.", image: "https://usercontent2.hubstatic.com/7249713.jpg", skill: 'Sr. Developer', github: null, linkedin: null, website: null, twitter: null, facebook: null,google_hangout: null, skype: null, paypal: null, billing_link: null, school: null, org: null, company: null, repl: null, codepen: null, codewars: null, queue_status: 'available', online: 'online' },
        { id: 3, username:'3', password:'$2a$10$Ynce0EsLn4dA1ESQyM0sgucKseOsYIIEdwg7OJAbvZ1vqmKM5GhA2', firstname: 'Bill', lastname: 'Gates', email: 'a@a.com', age: 26,  street: null, city: null, zip: null, state: null, country: null, phone: null, description: "I droped out of Harvard to create Microsoft and the Windows operating system. I really enjoy coding in C+.", tagline: "Success is a lousy teacher.", image: "https://pbs.twimg.com/profile_images/988775660163252226/XpgonN0X_400x400.jpg", skill: 'Sr. Developer', github: null, linkedin: null, website: null, twitter: null, facebook: null,google_hangout: null, skype: null, paypal: null, billing_link: null, school: null, org: null, company: null, repl: null, codepen: null, codewars: null, queue_status: 'available', online: 'online' },
        { id: 4, username:'4', password:'$2a$10$Ynce0EsLn4dA1ESQyM0sgucKseOsYIIEdwg7OJAbvZ1vqmKM5GhA2', firstname: 'Jeff', lastname: 'Bezos', email: 'a@a.com', age: 26,  street: null, city: null, zip: null, state: null, country: null, phone: null, description: "Learning to code and creating AWS is the best challenge of my life. Happy to host your Web needs.", tagline: "The only way to get out of a tight box is to invent your way out.", image: "http://www.gstatic.com/tv/thumb/persons/532529/532529_v9_bb.jpg", skill: 'Sr. Developer', github: null, linkedin: null, website: null, twitter: null, facebook: null,google_hangout: null, skype: null, paypal: null, billing_link: null, school: null, org: null, company: null, repl: null, codepen: null, codewars: null, queue_status: 'available', online: 'online' },
        { id: 5, username:'5', password:'$2a$10$Ynce0EsLn4dA1ESQyM0sgucKseOsYIIEdwg7OJAbvZ1vqmKM5GhA2', firstname: 'e', lastname: 'b', email: 'a@a.com', age: 26,  street: null, city: null, zip: null, state: null, country: null, phone: null, description: "I am a new developer and super excited to start getting help with iHelp", tagline: "I love JavaScipt", image: "https://media.licdn.com/dms/image/C5603AQH1JBVcGG9W6g/profile-displayphoto-shrink_200_200/0?e=1556755200&v=beta&t=ST8HB4WG63mJq973cm8G4XmY4Hewik457_L8G0yz0sQ", skill: 'New Developer', github: null, linkedin: null, website: null, twitter: null, facebook: null,google_hangout: null, skype: null, paypal: null, billing_link: null, school: null, org: null, company: null, repl: null, codepen: null, codewars: null, queue_status: 'available', online: 'online' },
        { id: 6, username:'6', password:'$2a$10$Ynce0EsLn4dA1ESQyM0sgucKseOsYIIEdwg7OJAbvZ1vqmKM5GhA2', firstname: 'f', lastname: 'b', email: 'a@a.com', age: 26,  street: null, city: null, zip: null, state: null, country: null, phone: null, description: "I am a new developer and super excited to start getting help with iHelp", tagline: "I love JavaScipt", image: "https://media.licdn.com/dms/image/C5603AQH1JBVcGG9W6g/profile-displayphoto-shrink_200_200/0?e=1556755200&v=beta&t=ST8HB4WG63mJq973cm8G4XmY4Hewik457_L8G0yz0sQ", skill: 'New Developer', github: null, linkedin: null, website: null, twitter: null, facebook: null,google_hangout: null, skype: null, paypal: null, billing_link: null, school: null, org: null, company: null, repl: null, codepen: null, codewars: null, queue_status: 'available', online: 'offline' },
        { id: 7, username:'7', password:'$2a$10$Ynce0EsLn4dA1ESQyM0sgucKseOsYIIEdwg7OJAbvZ1vqmKM5GhA2', firstname: 'g', lastname: 'b', email: 'a@a.com', age: 26,  street: null, city: null, zip: null, state: null, country: null, phone: null, description: "I am a new developer and super excited to start getting help with iHelp", tagline: "I love JavaScipt", image: "https://media.licdn.com/dms/image/C5603AQH1JBVcGG9W6g/profile-displayphoto-shrink_200_200/0?e=1556755200&v=beta&t=ST8HB4WG63mJq973cm8G4XmY4Hewik457_L8G0yz0sQ", skill: 'New Developer', github: null, linkedin: null, website: null, twitter: null, facebook: null,google_hangout: null, skype: null, paypal: null, billing_link: null, school: null, org: null, company: null, repl: null, codepen: null, codewars: null, queue_status: 'available', online: 'offline' },
        { id: 8, username:'8', password:'$2a$10$Ynce0EsLn4dA1ESQyM0sgucKseOsYIIEdwg7OJAbvZ1vqmKM5GhA2', firstname: 'h', lastname: 'b', email: 'a@a.com', age: 26,  street: null, city: null, zip: null, state: null, country: null, phone: null, description: "I am a new developer and super excited to start getting help with iHelp", tagline: "I love JavaScipt", image: "https://media.licdn.com/dms/image/C5603AQH1JBVcGG9W6g/profile-displayphoto-shrink_200_200/0?e=1556755200&v=beta&t=ST8HB4WG63mJq973cm8G4XmY4Hewik457_L8G0yz0sQ", skill: 'New Developer', github: null, linkedin: null, website: null, twitter: null, facebook: null,google_hangout: null, skype: null, paypal: null, billing_link: null, school: null, org: null, company: null, repl: null, codepen: null, codewars: null, queue_status: 'available', online: 'offline' },
        { id: 9, username:'9', password:'$2a$10$Ynce0EsLn4dA1ESQyM0sgucKseOsYIIEdwg7OJAbvZ1vqmKM5GhA2', firstname: 'i', lastname: 'b', email: 'a@a.com', age: 26,  street: null, city: null, zip: null, state: null, country: null, phone: null, description: "I am a new developer and super excited to start getting help with iHelp", tagline: "I love JavaScipt", image: "https://media.licdn.com/dms/image/C5603AQH1JBVcGG9W6g/profile-displayphoto-shrink_200_200/0?e=1556755200&v=beta&t=ST8HB4WG63mJq973cm8G4XmY4Hewik457_L8G0yz0sQ", skill: 'New Developer', github: null, linkedin: null, website: null, twitter: null, facebook: null,google_hangout: null, skype: null, paypal: null, billing_link: null, school: null, org: null, company: null, repl: null, codepen: null, codewars: null, queue_status: 'available', online: 'offline' },
        { id: 10, username:'10', password:'$2a$10$Ynce0EsLn4dA1ESQyM0sgucKseOsYIIEdwg7OJAbvZ1vqmKM5GhA2', firstname: 'j', lastname: 'b', email: 'a@a.com', age: 26,  street: null, city: null, zip: null, state: null, country: null, phone: null, description: "I am a new developer and super excited to start getting help with iHelp", tagline: "I love JavaScipt", image: "https://media.licdn.com/dms/image/C5603AQH1JBVcGG9W6g/profile-displayphoto-shrink_200_200/0?e=1556755200&v=beta&t=ST8HB4WG63mJq973cm8G4XmY4Hewik457_L8G0yz0sQ", skill: 'New Developer', github: null, linkedin: null, website: null, twitter: null, facebook: null,google_hangout: null, skype: null, paypal: null, billing_link: null, school: null, org: null, company: null, repl: null, codepen: null, codewars: null, queue_status: 'available', online: 'offline'},
        { id: 11, username:'cool', password:'$2a$10$Ynce0EsLn4dA1ESQyM0sgucKseOsYIIEdwg7OJAbvZ1vqmKM5GhA2', firstname: 'This GUY!!! ', lastname: 'is COOL', email: 'a@a.com', age: 26,  street: null, city: null, zip: null, state: null, country: null, phone: null, description: "I am a new developer and super excited to start getting help with iHelp", tagline: "I love JavaScipt", image: "https://media.licdn.com/dms/image/C5603AQH1JBVcGG9W6g/profile-displayphoto-shrink_200_200/0?e=1556755200&v=beta&t=ST8HB4WG63mJq973cm8G4XmY4Hewik457_L8G0yz0sQ", skill: 'New Developer', github: null, linkedin: null, website: null, twitter: null, facebook: null,google_hangout: null, skype: null, paypal: null, billing_link: null, school: null, org: null, company: null, repl: null, codepen: null, codewars: null, queue_status: 'available', online: 'offline' }

      ]);
    }).then(() => {
      return knex.raw(
        `SELECT setval('users_id_seq', (SELECT MAX(id) FROM users));`
      )
    })
};